server:
  port: 8181
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/adjoda-dev-realm
          jwk-set-uri: http://localhost:8080/realms/adjoda-dev-realm/protocol/openid-connect/certs

  datasource:
    url: jdbc:mysql://localhost:3306/nethelp
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: USER-SERVICE


